export const apiLink = 'https://norma.nomoreparties.space/api/ingredients';
export const mocData = [
    {
        "_id": "60d3b41abdacab0026a733c6",
        "name": "Краторная булка N-200i",
        "type": "bun",
        "proteins": 80,
        "fat": 24,
        "carbohydrates": 53,
        "calories": 420,
        "price": 1255,
        "image": "https://code.s3.yandex.net/react/code/bun-02.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
        "__v": 0
    },
    {
        "_id": "60d3b41abdacab0026a733ce",
        "name": "Соус традиционный галактический",
        "type": "sauce",
        "proteins": 42,
        "fat": 24,
        "carbohydrates": 42,
        "calories": 99,
        "price": 15,
        "image": "https://code.s3.yandex.net/react/code/sauce-03.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/sauce-03-large.png",
        "__v": 0
    },
    {
        "_id": "60d3b41abdacab0026a733c9",
        "name": "Мясо бессмертных моллюсков Protostomia",
        "type": "main",
        "proteins": 433,
        "fat": 244,
        "carbohydrates": 33,
        "calories": 420,
        "price": 1337,
        "image": "https://code.s3.yandex.net/react/code/meat-02.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/meat-02-large.png",
        "__v": 0
    },
    {
        "_id": "60d3b41abdacab0026a733d1",
        "name": "Плоды Фалленианского дерева",
        "type": "main",
        "proteins": 20,
        "fat": 5,
        "carbohydrates": 55,
        "calories": 77,
        "price": 874,
        "image": "https://code.s3.yandex.net/react/code/sp_1.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/sp_1-large.png",
        "__v": 0
    },
    {
        "_id": "60d3b41abdacab0026a733d0",
        "name": "Хрустящие минеральные кольца",
        "type": "main",
        "proteins": 808,
        "fat": 689,
        "carbohydrates": 609,
        "calories": 986,
        "price": 300,
        "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
        "__v": 0
    },
    {
        "_id": "60d3b41abdacab0026a733d0",
        "name": "Хрустящие минеральные кольца",
        "type": "main",
        "proteins": 808,
        "fat": 689,
        "carbohydrates": 609,
        "calories": 986,
        "price": 300,
        "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
        "__v": 0
    },
    {
        "_id": "60d3b41abdacab0026a733d0",
        "name": "Хрустящие минеральные кольца",
        "type": "main",
        "proteins": 808,
        "fat": 689,
        "carbohydrates": 609,
        "calories": 986,
        "price": 300,
        "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
        "__v": 0
    },
    {
        "_id": "60d3b41abdacab0026a733d0",
        "name": "Хрустящие минеральные кольца",
        "type": "main",
        "proteins": 808,
        "fat": 689,
        "carbohydrates": 609,
        "calories": 986,
        "price": 300,
        "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
        "__v": 0
    }];
